/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package securityport;

import Classes.ClassConecta;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.updateComponentTreeUI;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author User
 */
public class jFHome extends javax.swing.JFrame {

    /**
     * Creates new form jFHome
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     */
    public jFHome() throws ClassNotFoundException, InstantiationException, IllegalAccessException {
        initComponents();

        try {
            //ATUALIZA O LOOKANDFEEL'S PARA O LAF DO WINDOWS TESTAR NO MAC E LINUX)
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
            updateComponentTreeUI(this);

        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(jFHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        pessoasjButton = new javax.swing.JButton();
        consultaMoradoresjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        torresjButton = new javax.swing.JButton();
        apartamentosjButton = new javax.swing.JButton();
        cargosjButton = new javax.swing.JButton();
        tipoAcessoVisitantejButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeUsuariojLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logoffjMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        sairjMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        pessoasjMenuItem = new javax.swing.JMenuItem();
        cadastroVisitantesjMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        controlePortariajMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        cadastroTorrresjMenuItem = new javax.swing.JMenuItem();
        cadastroApartamentosjMenuItem = new javax.swing.JMenuItem();
        cadastroCargosjMenuItem = new javax.swing.JMenuItem();
        cadastroTipoAcessoVisitjMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastros", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, null, new java.awt.Color(0, 102, 204)));
        jPanel5.setForeground(new java.awt.Color(0, 102, 204));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        pessoasjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/user.png"))); // NOI18N
        pessoasjButton.setText("Pessoas");
        pessoasjButton.setFocusable(false);
        pessoasjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pessoasjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pessoasjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoasjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(pessoasjButton);

        consultaMoradoresjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/update_user.png"))); // NOI18N
        consultaMoradoresjButton.setText("Consulta Moradores");
        consultaMoradoresjButton.setFocusable(false);
        consultaMoradoresjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        consultaMoradoresjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        consultaMoradoresjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaMoradoresjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(consultaMoradoresjButton);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/testimonials.png"))); // NOI18N
        jButton1.setText("Cadastro visitantes");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastros base", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, null, new java.awt.Color(0, 109, 209)));

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        torresjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Tower_14-16.png"))); // NOI18N
        torresjButton.setText("Torres (Bloco)");
        torresjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        torresjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        torresjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torresjButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(torresjButton);

        apartamentosjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/folder_home.png"))); // NOI18N
        apartamentosjButton.setText("Apartamentos");
        apartamentosjButton.setFocusable(false);
        apartamentosjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        apartamentosjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        apartamentosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartamentosjButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(apartamentosjButton);

        cargosjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/binary-tree.png"))); // NOI18N
        cargosjButton.setText("Cargos");
        cargosjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cargosjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cargosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargosjButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(cargosjButton);

        tipoAcessoVisitantejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/color.png"))); // NOI18N
        tipoAcessoVisitantejButton.setText("Tipo acesso visitante");
        tipoAcessoVisitantejButton.setFocusable(false);
        tipoAcessoVisitantejButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tipoAcessoVisitantejButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tipoAcessoVisitantejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAcessoVisitantejButtonActionPerformed(evt);
            }
        });
        jToolBar2.add(tipoAcessoVisitantejButton);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Administrativo", jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 426, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Usuário Logado:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeUsuariojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeUsuariojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator1)
        );

        jMenu1.setText("Arquivo");

        logoffjMenuItem.setText("Alterar usuario");
        logoffjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoffjMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(logoffjMenuItem);
        jMenu1.add(jSeparator3);

        sairjMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        sairjMenuItem.setText("Sair");
        sairjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(sairjMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Administrativo");

        jMenu5.setText("Controles");

        pessoasjMenuItem.setText("Pessoas");
        pessoasjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoasjMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(pessoasjMenuItem);

        cadastroVisitantesjMenuItem.setText("Cadastro Visitantes");
        cadastroVisitantesjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroVisitantesjMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(cadastroVisitantesjMenuItem);
        jMenu5.add(jSeparator2);

        controlePortariajMenuItem.setText("Controle portaria");
        controlePortariajMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlePortariajMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(controlePortariajMenuItem);

        jMenu4.add(jMenu5);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Cadastros base");

        cadastroTorrresjMenuItem.setText("Cadastro torres (Bloco)");
        cadastroTorrresjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroTorrresjMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(cadastroTorrresjMenuItem);

        cadastroApartamentosjMenuItem.setText("Cadastro apartamentos");
        cadastroApartamentosjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroApartamentosjMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(cadastroApartamentosjMenuItem);

        cadastroCargosjMenuItem.setText("Cadastro cargos");
        cadastroCargosjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCargosjMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(cadastroCargosjMenuItem);

        cadastroTipoAcessoVisitjMenuItem.setText("Cadastro tipo acesso visitante");
        cadastroTipoAcessoVisitjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroTipoAcessoVisitjMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(cadastroTipoAcessoVisitjMenuItem);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ClassConecta conecta = new ClassConecta();
    
    //******************************************
    //dados do usuario logado;
    Integer codigo_pessoa_usuario;
    String nome_usuario;
    String usuario;
    String nivel_acesso;
//******************************************


    private void sairjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairjMenuItemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            ClassConecta.conecta();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir conexão com o banco de dados.\n"+e,
                    "Mensgame do sistema", JOptionPane.ERROR_MESSAGE);
        }
        nomeUsuariojLabel.setText(usuario);
    }//GEN-LAST:event_formWindowOpened

    private void cargosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargosjButtonActionPerformed
        // TODO add your handling code here:
        jFCargos oFormCargo = new jFCargos();
        
        oFormCargo.setTitle("Cadastro de cargos");
        oFormCargo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormCargo.setLocationRelativeTo(null);
        oFormCargo.setModal(true);
        oFormCargo.pack();
        oFormCargo.setVisible(true);
    }//GEN-LAST:event_cargosjButtonActionPerformed

    private void torresjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torresjButtonActionPerformed
        // TODO add your handling code here:
        jFTorres oFormTorre = new jFTorres();
        
        oFormTorre.setTitle("Cadastro de torres");
        oFormTorre.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormTorre.setLocationRelativeTo(null);
        oFormTorre.setModal(true);
        oFormTorre.pack();
        oFormTorre.setVisible(true);
    }//GEN-LAST:event_torresjButtonActionPerformed

    private void apartamentosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartamentosjButtonActionPerformed
        // TODO add your handling code here:
        jFApartamentos oFormAP = new jFApartamentos();
        
        oFormAP.setTitle("Cadastro de apartamentos");
        oFormAP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormAP.setLocationRelativeTo(null);
        oFormAP.setModal(true);
        oFormAP.pack();
        oFormAP.setVisible(true);
    }//GEN-LAST:event_apartamentosjButtonActionPerformed

    private void pessoasjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoasjButtonActionPerformed
        // TODO add your handling code here:
        jFPessoas oForm = new jFPessoas();
        
        oForm.setTitle("Cadastro de pessoas");
        oForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oForm.setLocationRelativeTo(null);
        oForm.setResizable(false);
        oForm.pack();
        oForm.setVisible(true);
    }//GEN-LAST:event_pessoasjButtonActionPerformed

    private void consultaMoradoresjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaMoradoresjButtonActionPerformed
        // TODO add your handling code here:
        jFConsultaMoradores oFormBuscaMorador = new jFConsultaMoradores();
        
        oFormBuscaMorador.setTitle("Consulta Moradores");
        oFormBuscaMorador.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormBuscaMorador.setLocationRelativeTo(null);
        oFormBuscaMorador.pack();
        oFormBuscaMorador.setVisible(true);
    }//GEN-LAST:event_consultaMoradoresjButtonActionPerformed

    private void cadastroTipoAcessoVisitjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroTipoAcessoVisitjMenuItemActionPerformed
        // TODO add your handling code here:
        jFTipoAcessoVisitante oFormTipAcessVisitor = new jFTipoAcessoVisitante();
        
        oFormTipAcessVisitor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormTipAcessVisitor.setLocationRelativeTo(null);
        oFormTipAcessVisitor.pack();
        oFormTipAcessVisitor.setVisible(true);
    }//GEN-LAST:event_cadastroTipoAcessoVisitjMenuItemActionPerformed

    private void cadastroVisitantesjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroVisitantesjMenuItemActionPerformed
        // TODO add your handling code here:
        jFCadastroPessoaVisitante oFormCadVisitor = new jFCadastroPessoaVisitante();
        
        oFormCadVisitor.recebe_codigo_pessoa_usuario = codigo_pessoa_usuario;
        oFormCadVisitor.recebe_nivel_acesso = nivel_acesso;
        
        oFormCadVisitor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormCadVisitor.setLocationRelativeTo(null);
        oFormCadVisitor.setModal(true);
        oFormCadVisitor.pack();
        oFormCadVisitor.setVisible(true);
    }//GEN-LAST:event_cadastroVisitantesjMenuItemActionPerformed

    private void controlePortariajMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlePortariajMenuItemActionPerformed
        // TODO add your handling code here:
        jFVisitantes oPortaria = new jFVisitantes();
        
        oPortaria.recebe_codigo_usuario = codigo_pessoa_usuario;
        oPortaria.recebe_nivel_acesso = nivel_acesso;
        
        oPortaria.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oPortaria.setLocationRelativeTo(null);
//        oPortaria.setModal(true);
        oPortaria.pack();
        oPortaria.setVisible(true);
    }//GEN-LAST:event_controlePortariajMenuItemActionPerformed

    private void cadastroTorrresjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroTorrresjMenuItemActionPerformed
        // TODO add your handling code here:
        jFTorres oFormTorre = new jFTorres();
        
        oFormTorre.setTitle("Cadastro de torres");
        oFormTorre.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormTorre.setLocationRelativeTo(null);
        oFormTorre.setModal(true);
        oFormTorre.pack();
        oFormTorre.setVisible(true);
    }//GEN-LAST:event_cadastroTorrresjMenuItemActionPerformed

    private void cadastroApartamentosjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroApartamentosjMenuItemActionPerformed
        // TODO add your handling code here:
        jFApartamentos oFormAP = new jFApartamentos();
        
        oFormAP.setTitle("Cadastro de apartamentos");
        oFormAP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormAP.setLocationRelativeTo(null);
        oFormAP.setModal(true);
        oFormAP.pack();
        oFormAP.setVisible(true);
    }//GEN-LAST:event_cadastroApartamentosjMenuItemActionPerformed

    private void cadastroCargosjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCargosjMenuItemActionPerformed
        // TODO add your handling code here:
        jFCargos oFormCargo = new jFCargos();
        
        oFormCargo.setTitle("Cadastro de cargos");
        oFormCargo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormCargo.setLocationRelativeTo(null);
        oFormCargo.setModal(true);
        oFormCargo.pack();
        oFormCargo.setVisible(true);
    }//GEN-LAST:event_cadastroCargosjMenuItemActionPerformed

    private void pessoasjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoasjMenuItemActionPerformed
        // TODO add your handling code here:
        jFPessoas oForm = new jFPessoas();
        
        oForm.setTitle("Cadastro de pessoas");
        oForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oForm.setLocationRelativeTo(null);
        oForm.setResizable(false);
        oForm.pack();
        oForm.setVisible(true);
    }//GEN-LAST:event_pessoasjMenuItemActionPerformed

    private void tipoAcessoVisitantejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAcessoVisitantejButtonActionPerformed
        // TODO add your handling code here:
        jFTipoAcessoVisitante oFormTipAcessVisitor = new jFTipoAcessoVisitante();
        
        oFormTipAcessVisitor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormTipAcessVisitor.setLocationRelativeTo(null);
        oFormTipAcessVisitor.pack();
        oFormTipAcessVisitor.setVisible(true);
    }//GEN-LAST:event_tipoAcessoVisitantejButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jFCadastroPessoaVisitante oFormCadVisitor = new jFCadastroPessoaVisitante();
        
        oFormCadVisitor.recebe_codigo_pessoa_usuario = codigo_pessoa_usuario;
        oFormCadVisitor.recebe_nivel_acesso = nivel_acesso;
        
        oFormCadVisitor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormCadVisitor.setLocationRelativeTo(null);
        oFormCadVisitor.setModal(true);
        oFormCadVisitor.pack();
        oFormCadVisitor.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logoffjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoffjMenuItemActionPerformed
        try {
            jFLogin oFormLogin = new jFLogin();
            
            oFormLogin.setLocationRelativeTo(null);
            oFormLogin.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            oFormLogin.pack();
            oFormLogin.setVisible(true);
            this.dispose();
            
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(jFHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_logoffjMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new jFHome().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
                    Logger.getLogger(jFHome.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apartamentosjButton;
    private javax.swing.JMenuItem cadastroApartamentosjMenuItem;
    private javax.swing.JMenuItem cadastroCargosjMenuItem;
    private javax.swing.JMenuItem cadastroTipoAcessoVisitjMenuItem;
    private javax.swing.JMenuItem cadastroTorrresjMenuItem;
    private javax.swing.JMenuItem cadastroVisitantesjMenuItem;
    private javax.swing.JButton cargosjButton;
    private javax.swing.JButton consultaMoradoresjButton;
    private javax.swing.JMenuItem controlePortariajMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem logoffjMenuItem;
    private javax.swing.JLabel nomeUsuariojLabel;
    private javax.swing.JButton pessoasjButton;
    private javax.swing.JMenuItem pessoasjMenuItem;
    private javax.swing.JMenuItem sairjMenuItem;
    private javax.swing.JButton tipoAcessoVisitantejButton;
    private javax.swing.JButton torresjButton;
    // End of variables declaration//GEN-END:variables
}
