/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package securityport;

import Classes.ClassConecta;
import Classes.EncriptaSenha;
import Classes.Usuarios;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.updateComponentTreeUI;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author User
 */
public class jFLogin extends javax.swing.JFrame {

    /**
     * Creates new form jFLogin
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     */
    public jFLogin() throws ClassNotFoundException, InstantiationException, IllegalAccessException {
        initComponents();
        
        try {
            //ATUALIZA O LOOKANDFEEL'S PARA O LAF DO WINDOWS TESTAR NO MAC E LINUX)
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
            updateComponentTreeUI(this);

        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(jFHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setLocationRelativeTo(null);
        
        
        //======================================================================================================================================================        
        JRootPane acessoSistema = getRootPane();
        acessoSistema.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "ACESSO_SISTEMA");
        acessoSistema.getRootPane().getActionMap().put("ACESSO_SISTEMA", new AbstractAction("ACESSO_SISTEMA") {

            @Override
            public void actionPerformed(ActionEvent e) {
                entrarjLabelMouseClicked(null);
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usuariojTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        senhajPasswordField = new javax.swing.JPasswordField();
        entrarjLabel = new javax.swing.JLabel();
        sairjLabel = new javax.swing.JLabel();
        conexaojLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Security Port");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/file_locked.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Usuário");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Senha");

        entrarjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icone entrar.png"))); // NOI18N
        entrarjLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrarjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarjLabelMouseClicked(evt);
            }
        });

        sairjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icone sair_login.png"))); // NOI18N
        sairjLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sairjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairjLabelMouseClicked(evt);
            }
        });

        conexaojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icone conexao.png"))); // NOI18N
        conexaojLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        conexaojLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conexaojLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(conexaojLabel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(senhajPasswordField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(entrarjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sairjLabel))
                    .addComponent(usuariojTextField))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(senhajPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entrarjLabel)
                    .addComponent(sairjLabel)
                    .addComponent(conexaojLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ClassConecta conecta = new ClassConecta();
    
    String senha;//pega a senha do campo password, crptografa e verifica com o recebe senha
    String recebe_senha; // recebe a senha para verificação
    String usuario;
    Integer codigo_usuario_pessoa;
    String nome_pessoa;
    String nivel_acesso;
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            ClassConecta.conecta();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir conexão com o banco de dados\n"+e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowOpened

    private void conexaojLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conexaojLabelMouseClicked
        // TODO add your handling code here:
        jFConexao oFormConexao = new jFConexao();
        
        oFormConexao.setTitle("Configurar conexão");
        oFormConexao.setLocationRelativeTo(null);
        oFormConexao.pack();
        oFormConexao.setModal(true);
        oFormConexao.setVisible(true);
    }//GEN-LAST:event_conexaojLabelMouseClicked

    private void entrarjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarjLabelMouseClicked
        // TODO add your handling code here:
        //resgata a senha do banco de acordo com o usuário digitado e guarda na variavel recebe_senha para verificação.
        recebe_senha = null;
        
        try {
            Usuarios oUsuario = new Usuarios();
            ResultSet rs;
            oUsuario.setNome_usuario(usuariojTextField.getText().trim().toUpperCase());
            rs = oUsuario.getConsultar(conecta);
            while (rs.next()) {
                recebe_senha = rs.getString("SENHA");
                usuario = rs.getString("NOME_USUARIO");
                codigo_usuario_pessoa = rs.getInt("CODIGO_PESSOA_USUARIO");
                nome_pessoa = rs.getString("NOME_PESSOA");
                nivel_acesso = rs.getString("NIVEL_ACESSO");
            }
        } catch (SQLException ex) {
            Logger.getLogger(jFLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
//==============================================================================================================================
        
        //pega a senha do campo senha e criptografa
        // CRIPTOGRAFA SENHA
        senha = new String(senhajPasswordField.getPassword()); //CRIA UMA VARIAVEL TIPO STRING E PEGA A PASSWORD
        EncriptaSenha.encripta(senha);                           //ENVIA A SENHA DA VARIAVEL SENHA PARA A CLASSE ENCRIPTA SENHA E REALIZAA CRIPTOGRAFIA
        System.out.println(EncriptaSenha.encripta(senha));
        System.out.println(recebe_senha);
        
        System.out.println("\n");
        System.out.println(codigo_usuario_pessoa);
        System.out.println(nome_pessoa);
        System.out.println(usuario);
        System.out.println(nivel_acesso);

 //==================================================================================================================================       
        if(senhajPasswordField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Atenção!\n<html><body>O campo <b>\"Senha\" </b>é obrigatório</body></html>", 
            "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else if (usuariojTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Atenção!\n<html><body>O campo <b>\"Usuário\" </b>é obrigatório</body></html>", 
            "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else if(!EncriptaSenha.encripta(senha).equals(recebe_senha)){
            JOptionPane.showMessageDialog(null, "A senha ou o usuário não conferem");
            usuariojTextField.setText("");
            senhajPasswordField.setText("");
            usuariojTextField.grabFocus();
        }else{
            
            try {
                    jFHome oFormHome = new jFHome();
                    
                    oFormHome.codigo_pessoa_usuario = codigo_usuario_pessoa;
                    oFormHome.nome_usuario = nome_pessoa;
                    oFormHome.usuario = usuario;
                    oFormHome.nivel_acesso = nivel_acesso;
                    
                    oFormHome.setLocationRelativeTo(null);
                    oFormHome.pack();
                    oFormHome.setVisible(true);
                    oFormHome.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    this.dispose();

            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException e) {
                JOptionPane.showMessageDialog(null, "Erro ao realizar o login\n"+e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
            }
 
        }
    }//GEN-LAST:event_entrarjLabelMouseClicked

    private void sairjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairjLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairjLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new jFLogin().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
                    Logger.getLogger(jFLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conexaojLabel;
    private javax.swing.JLabel entrarjLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel sairjLabel;
    private javax.swing.JPasswordField senhajPasswordField;
    private javax.swing.JTextField usuariojTextField;
    // End of variables declaration//GEN-END:variables
}
