/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package securityport;

import Classes.ClassConecta;
import Classes.Funcoes;
import Classes.Pessoas;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class jFPessoas extends javax.swing.JFrame {

    /**
     * Creates new form jFPessoas
     */
    public jFPessoas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buscarjButton = new javax.swing.JButton();
        novojButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        salvarjButton = new javax.swing.JButton();
        salvarMaisjButton = new javax.swing.JButton();
        alterarjButton = new javax.swing.JButton();
        excluirjButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        cancelarjButton = new javax.swing.JButton();
        limparjButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomePessoajTextField = new javax.swing.JTextField();
        statusjComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        dataCadastrojFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradePessoasjTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cadastroMoradoresjButton = new javax.swing.JButton();
        cadastroFuncionariosjButton = new javax.swing.JButton();
        cadastro_visitantesjButton = new javax.swing.JButton();
        cadastrousuariosjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buscarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscar.png"))); // NOI18N
        buscarjButton.setText("Buscar");
        buscarjButton.setFocusable(false);
        buscarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(buscarjButton);

        novojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/new2.png"))); // NOI18N
        novojButton.setText("Novo");
        novojButton.setFocusable(false);
        novojButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        novojButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        novojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novojButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(novojButton);

        editarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        editarjButton.setText("Editar");
        editarjButton.setFocusable(false);
        editarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(editarjButton);
        jToolBar1.add(jSeparator1);

        salvarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save.png"))); // NOI18N
        salvarjButton.setText("Salvar");
        salvarjButton.setFocusable(false);
        salvarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(salvarjButton);

        salvarMaisjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save_plus.png"))); // NOI18N
        salvarMaisjButton.setText("Salvar+");
        salvarMaisjButton.setFocusable(false);
        salvarMaisjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarMaisjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(salvarMaisjButton);

        alterarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save2.png"))); // NOI18N
        alterarjButton.setText("Alterar");
        alterarjButton.setFocusable(false);
        alterarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alterarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alterarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(alterarjButton);

        excluirjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/delete.png"))); // NOI18N
        excluirjButton.setText("Excluir");
        excluirjButton.setFocusable(false);
        excluirjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        excluirjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(excluirjButton);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator4);

        cancelarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cancel.png"))); // NOI18N
        cancelarjButton.setText("Cancelar");
        cancelarjButton.setFocusable(false);
        cancelarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(cancelarjButton);

        limparjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clear.png"))); // NOI18N
        limparjButton.setText("Limpar");
        limparjButton.setFocusable(false);
        limparjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        limparjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        limparjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(limparjButton);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome pessoa");

        nomePessoajTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomePessoajTextFieldKeyReleased(evt);
            }
        });

        statusjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "INATIVO" }));
        statusjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusjComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Status");

        dataCadastrojFormattedTextField.setEditable(false);
        try {
            dataCadastrojFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Data cadastro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomePessoajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dataCadastrojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomePessoajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataCadastrojFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gradePessoasjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id#", "Nome pessoa", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradePessoasjTable.getTableHeader().setReorderingAllowed(false);
        gradePessoasjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradePessoasjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradePessoasjTable);
        if (gradePessoasjTable.getColumnModel().getColumnCount() > 0) {
            gradePessoasjTable.getColumnModel().getColumn(0).setResizable(false);
            gradePessoasjTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            gradePessoasjTable.getColumnModel().getColumn(1).setResizable(false);
            gradePessoasjTable.getColumnModel().getColumn(1).setPreferredWidth(250);
            gradePessoasjTable.getColumnModel().getColumn(2).setResizable(false);
            gradePessoasjTable.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cadastroMoradoresjButton.setText("Moradores");
        cadastroMoradoresjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroMoradoresjButtonActionPerformed(evt);
            }
        });

        cadastroFuncionariosjButton.setText("Funcionários");

        cadastro_visitantesjButton.setText("Visitantes");

        cadastrousuariosjButton.setText("Usuários");
        cadastrousuariosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrousuariosjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroMoradoresjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastroFuncionariosjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastro_visitantesjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrousuariosjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroMoradoresjButton)
                    .addComponent(cadastroFuncionariosjButton)
                    .addComponent(cadastro_visitantesjButton)
                    .addComponent(cadastrousuariosjButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ClassConecta conecta = new ClassConecta();
    
    protected int codigo_click_pessoa;
    
    
    public void getGradePessoa() throws ParseException{
       //Consultar pedidos
        Pessoas oPessoa = new Pessoas();

        if ( nomePessoajTextField.getText().length() > 0 ){
            oPessoa.setNome_pessoa(nomePessoajTextField.getText()+"%");
        }

        ResultSet resultSet = null;

        String[] colunasTabela = new String[]{"#Id", "Nome Pessoa", "Tipo Pessoa"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        gradePessoasjTable.setModel(modeloTabela);
        gradePessoasjTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        gradePessoasjTable.getColumnModel().getColumn(1).setPreferredWidth(250);
        gradePessoasjTable.getColumnModel().getColumn(2).setPreferredWidth(50);

//        gradePessoajTable.setDefaultRenderer(Object.class, new ColorRenderer()); // DEIXA A GRADE ZEBRADA

try {
            //pega o status e seta na filtro da grade Pessoa
            String status = statusjComboBox.getSelectedItem().toString();
            oPessoa.setStatus(status);
            resultSet = oPessoa.getConsultar(conecta);
            if (resultSet.getRow() == 1){
             resultSet.first();
            }


        } catch (SQLException ex) {
            Logger.getLogger(Pessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            while (resultSet.next()) {

                //Formatar data
//                Date cadastro = resultSet.getDate("DATA_CADASTRO");
//
//                String dataCadastro;
//                if (cadastro != null){
//                SimpleDateFormat formatoDataLanc = new SimpleDateFormat("dd/MM/yyyy");
//                dataCadastro = formatoDataLanc.format(cadastro);
//                }else{
//                dataCadastro = "";
//                }
                //Fim formatação

                modeloTabela.addRow(new String[]{
                    Funcoes.getCodigoFormat(resultSet.getInt("CODIGO_PESSOA")),
                    resultSet.getString("NOME_PESSOA"),
//                    dataCadastro,
                    resultSet.getString("STATUS"),
                    
                });

            }

        } catch (SQLException ex) {
            Logger.getLogger(Pessoas.class.getName()).log(Level.SEVERE, null, ex);
        }

           }
    
    
    public void getFieldPessoas(int codigo_click_pessoa) throws ParseException{

        Pessoas oPessoa = new Pessoas();
        ResultSet rs;
        oPessoa.setCodigo_pessoa(codigo_click_pessoa);

        try {
            rs = oPessoa.getConsultar(conecta);
            rs.next();

            //Pegar campos
            nomePessoajTextField.setText(rs.getString("NOME_PESSOA"));
            dataCadastrojFormattedTextField.setValue(Funcoes.getDataFormat(rs.getDate("DATA_CADASTRO")));
            statusjComboBox.setSelectedItem(rs.getString("STATUS"));
        } catch (SQLException ex) {
            Logger.getLogger(Pessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        buscarjButton.setVisible(true);
        novojButton.setVisible(true);
        editarjButton.setVisible(false);
        salvarjButton.setVisible(false);
        salvarMaisjButton.setVisible(false);
        alterarjButton.setVisible(false);
        excluirjButton.setVisible(false);
        cancelarjButton.setVisible(false);
        nomePessoajTextField.grabFocus();
        //-------------------------------------
        cadastroMoradoresjButton.setEnabled(false);
        cadastroFuncionariosjButton.setEnabled(false);
        cadastro_visitantesjButton.setEnabled(false);
        cadastrousuariosjButton.setEnabled(false);
        
        try {
            ClassConecta.conecta();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar com o banco de dados\n"+e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
        try {
            dataCadastrojFormattedTextField.setText(Funcoes.getNowBR());
        } catch (ParseException ex) {
            Logger.getLogger(jFPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
        buscarjButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowOpened

    private void novojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novojButtonActionPerformed
        // TODO add your handling code here:
        buscarjButton.setVisible(true);
        novojButton.setVisible(false);
        editarjButton.setVisible(false);
        salvarjButton.setVisible(true);
        salvarMaisjButton.setVisible(true);
        alterarjButton.setVisible(false);
        excluirjButton.setVisible(false);
        cancelarjButton.setVisible(true);
        nomePessoajTextField.grabFocus();
        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(jFPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
        limparjButtonActionPerformed(evt);
    }//GEN-LAST:event_novojButtonActionPerformed

    private void limparjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparjButtonActionPerformed
        // TODO add your handling code here:
        nomePessoajTextField.setText("");
        statusjComboBox.setSelectedItem("ATIVO");
        try {
            dataCadastrojFormattedTextField.setText(Funcoes.getNowBR());
        } catch (ParseException ex) {
            Logger.getLogger(jFPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_limparjButtonActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        if(nomePessoajTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Atenção!\nInsira um nome", "Mensagem do sistema", JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                buscarjButton.setVisible(true);
                novojButton.setVisible(true);
                editarjButton.setVisible(false);
                salvarjButton.setVisible(false);
                salvarMaisjButton.setVisible(false);
                alterarjButton.setVisible(false);
                excluirjButton.setVisible(false);
                cancelarjButton.setVisible(false);
                
                Pessoas oPessoa = new Pessoas();
                
                oPessoa.setNome_pessoa(nomePessoajTextField.getText().trim().toUpperCase());
                oPessoa.setStatus(statusjComboBox.getSelectedItem().toString());
                oPessoa.setData_cadastro(Funcoes.getDataFormatBR(dataCadastrojFormattedTextField.getText()));
                oPessoa.setCadastrar();           
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar\n"+e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
            }
            try {
            getGradePessoa();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar a grade Pessoa\n"+e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void buscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarjButtonActionPerformed
        // TODO add your handling code here:
        try {
            getGradePessoa();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar a grade Pessoa\n"+e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buscarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setVisible(false);
        editarjButton.setVisible(false);
        salvarjButton.setVisible(false);
        salvarMaisjButton.setVisible(false);
        alterarjButton.setVisible(true);
        excluirjButton.setVisible(true);
        cancelarjButton.setVisible(true);
        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(jFPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void gradePessoasjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradePessoasjTableMouseClicked
        // TODO add your handling code here:
        editarjButton.setVisible(true);
        
        cadastroMoradoresjButton.setEnabled(true);
        cadastroFuncionariosjButton.setEnabled(true);
        cadastro_visitantesjButton.setEnabled(true);
        cadastrousuariosjButton.setEnabled(true);
        
        codigo_click_pessoa = Integer.parseInt(gradePessoasjTable.getValueAt(gradePessoasjTable.getSelectedRow(), 0).toString());  
        try {
            getFieldPessoas(codigo_click_pessoa);
        } catch (ParseException ex) {
            Logger.getLogger(Pessoas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao pegar dados da grade\n"+ex, "Mensagen do sistema", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_gradePessoasjTableMouseClicked

    private void nomePessoajTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomePessoajTextFieldKeyReleased
        // TODO add your handling code here:
        try {
                Pessoas oPessoa = new Pessoas();
                oPessoa.setNome_pessoa(nomePessoajTextField.getText());
                ResultSet rs = null;
                rs = oPessoa.getConsultar(conecta);
                getGradePessoa();
            } catch (    ParseException | SQLException ex) {
                Logger.getLogger(Pessoas.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_nomePessoajTextFieldKeyReleased

    private void alterarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarjButtonActionPerformed
        // TODO add your handling code here:
        if(nomePessoajTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Insira um nome co campo Pessoa", "Mensagem do sistema", JOptionPane.INFORMATION_MESSAGE);
                        
        }else{
            try {
                buscarjButton.setVisible(true);
                novojButton.setVisible(true);
                editarjButton.setVisible(false);
                salvarjButton.setVisible(false);
                salvarMaisjButton.setVisible(false);
                alterarjButton.setVisible(false);
                excluirjButton.setVisible(false);
                cancelarjButton.setVisible(false);
                
                Pessoas oPessoa = new Pessoas();
                
                oPessoa.setCodigo_pessoa(codigo_click_pessoa);
                
                oPessoa.setNome_pessoa(nomePessoajTextField.getText().trim().toUpperCase());
                oPessoa.setData_cadastro(Funcoes.getDataFormatBR(dataCadastrojFormattedTextField.getText()));
                oPessoa.setStatus(statusjComboBox.getSelectedItem().toString());
                oPessoa.setAlterar(conecta);
            } catch (Exception e) {
            }
            try {
                getGradePessoa();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao carregar a grade\n"+e, "Mensagen do sistema", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_alterarjButtonActionPerformed

    private void statusjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusjComboBoxActionPerformed
        // TODO add your handling code here:
        if(!alterarjButton.isVisible()){
            buscarjButtonActionPerformed(evt);
        }
        
    }//GEN-LAST:event_statusjComboBoxActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        // TODO add your handling code here:
        Object[] options = {"Sim", "Não"};
        int sd =
                JOptionPane.showOptionDialog(null, "Deseja realmente EXCLUIR esse registro?", "Confirmação!", JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        if (sd != 0) {
            return;
        }
        
        try {
            cancelarjButtonActionPerformed(evt);
        
            Pessoas oPessoas = new Pessoas();
        
            oPessoas.setCodigo_pessoa(codigo_click_pessoa);
            oPessoas.setExcluir(conecta);
        
            limparjButtonActionPerformed(evt); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir registro\n"+e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE); 
        }
        try {
                getGradePessoa();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao carregar a grade\n"+e, "Mensagen do sistema", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_excluirjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
        buscarjButton.setVisible(true);
        novojButton.setVisible(true);
        editarjButton.setVisible(false);
        salvarjButton.setVisible(false);
        salvarMaisjButton.setVisible(false);
        alterarjButton.setVisible(false);
        excluirjButton.setVisible(false);
        cancelarjButton.setVisible(false);
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void cadastroMoradoresjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroMoradoresjButtonActionPerformed
        // TODO add your handling code here:
        jFMoradores oFormMorador = new jFMoradores();
        
        oFormMorador.recebe_codigo_pessoa = codigo_click_pessoa;
        oFormMorador.recebe_nome_pessoa = nomePessoajTextField.getText().trim().toUpperCase();
        
        oFormMorador.setTitle("Cadastro de pessoas");
        oFormMorador.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        oFormMorador.setLocationRelativeTo(null);
        oFormMorador.setResizable(false);
        oFormMorador.pack();
        oFormMorador.setVisible(true);
    }//GEN-LAST:event_cadastroMoradoresjButtonActionPerformed

    private void cadastrousuariosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrousuariosjButtonActionPerformed
        // TODO add your handling code here:
        jFUsuarios oUsuario = new jFUsuarios();
        
        oUsuario.recebe_codigo_pessoa = codigo_click_pessoa;
        oUsuario.recebe_nome_pessoa = nomePessoajTextField.getText().trim().toUpperCase();
        
        oUsuario.setTitle("Cadastro de usuários");
        oUsuario.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        oUsuario.setLocationRelativeTo(null);
        oUsuario.setModal(true);
        oUsuario.pack();
        oUsuario.setVisible(true);
    }//GEN-LAST:event_cadastrousuariosjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jFPessoas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarjButton;
    private javax.swing.JButton buscarjButton;
    private javax.swing.JButton cadastroFuncionariosjButton;
    private javax.swing.JButton cadastroMoradoresjButton;
    private javax.swing.JButton cadastro_visitantesjButton;
    private javax.swing.JButton cadastrousuariosjButton;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JFormattedTextField dataCadastrojFormattedTextField;
    private javax.swing.JButton editarjButton;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JTable gradePessoasjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton limparjButton;
    private javax.swing.JTextField nomePessoajTextField;
    private javax.swing.JButton novojButton;
    private javax.swing.JButton salvarMaisjButton;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JComboBox statusjComboBox;
    // End of variables declaration//GEN-END:variables
}
