/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package securityport;

import Classes.ClassConecta;
import Classes.EncriptaSenha;
import Classes.Funcoes;
import Classes.Pessoas;
import Classes.Usuarios;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class jFUsuarios extends javax.swing.JDialog {

    /**
     * Creates new form jFUsuarios
     */
    public jFUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buscarjButton = new javax.swing.JButton();
        novojButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        editarjButton = new javax.swing.JButton();
        salvarjButton = new javax.swing.JButton();
        alterarjButton = new javax.swing.JButton();
        excluirjButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        cancelarjButton = new javax.swing.JButton();
        limparjButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeusuariosjTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nome_pessoajTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeUsuariojTextField = new javax.swing.JTextField();
        senhajPasswordField = new javax.swing.JPasswordField();
        repetirSenhajPasswordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        nivelAcessojComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buscarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscar.png"))); // NOI18N
        buscarjButton.setText("Buscar");
        buscarjButton.setFocusable(false);
        buscarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(buscarjButton);

        novojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/new2.png"))); // NOI18N
        novojButton.setText("Novo");
        novojButton.setFocusable(false);
        novojButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        novojButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        novojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novojButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(novojButton);
        jToolBar1.add(jSeparator1);

        editarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        editarjButton.setText("Editar");
        editarjButton.setFocusable(false);
        editarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(editarjButton);

        salvarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save.png"))); // NOI18N
        salvarjButton.setText("Salvar");
        salvarjButton.setFocusable(false);
        salvarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(salvarjButton);

        alterarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/save2.png"))); // NOI18N
        alterarjButton.setText("Alterar");
        alterarjButton.setFocusable(false);
        alterarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alterarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alterarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(alterarjButton);

        excluirjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/delete.png"))); // NOI18N
        excluirjButton.setText("Excluir");
        excluirjButton.setFocusable(false);
        excluirjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        excluirjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(excluirjButton);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator4);

        cancelarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Cancel.png"))); // NOI18N
        cancelarjButton.setText("Cancelar");
        cancelarjButton.setFocusable(false);
        cancelarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(cancelarjButton);

        limparjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clear.png"))); // NOI18N
        limparjButton.setText("Limpar");
        limparjButton.setFocusable(false);
        limparjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        limparjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(limparjButton);

        gradeusuariosjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id#", "Usuário", "Nível acesso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradeusuariosjTable.getTableHeader().setReorderingAllowed(false);
        gradeusuariosjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeusuariosjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradeusuariosjTable);
        if (gradeusuariosjTable.getColumnModel().getColumnCount() > 0) {
            gradeusuariosjTable.getColumnModel().getColumn(0).setResizable(false);
            gradeusuariosjTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            gradeusuariosjTable.getColumnModel().getColumn(1).setResizable(false);
            gradeusuariosjTable.getColumnModel().getColumn(1).setPreferredWidth(180);
            gradeusuariosjTable.getColumnModel().getColumn(2).setResizable(false);
            gradeusuariosjTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jLabel1.setText("Nome pessoa");

        nome_pessoajTextField.setEditable(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome usuário:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Senha:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Rep. senha:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Acesso:");

        nivelAcessojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "ADMINISTRADOR", "USUARIO_ADM", "OPERADOR" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome_pessoajTextField)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeUsuariojTextField)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(senhajPasswordField)
                                    .addComponent(repetirSenhajPasswordField)
                                    .addComponent(nivelAcessojComboBox, 0, 185, Short.MAX_VALUE))
                                .addGap(0, 198, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome_pessoajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeUsuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(senhajPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(repetirSenhajPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nivelAcessojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro de usuários", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    ClassConecta conecta = new ClassConecta();
    
    public int recebe_codigo_pessoa;
    public String recebe_nome_pessoa;
    protected int codigo_click_usuario;
    
    public void getGradeusuarios() throws ParseException{
       //Consultar Usuario
        Usuarios oUsuario = new Usuarios();

        ResultSet resultSet = null;

        String[] colunasTabela = new String[]{"#Id", "Usuário", "Nivel acesso"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        gradeusuariosjTable.setModel(modeloTabela);
        gradeusuariosjTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        gradeusuariosjTable.getColumnModel().getColumn(1).setPreferredWidth(180);
        gradeusuariosjTable.getColumnModel().getColumn(2).setPreferredWidth(100);

//        gradePessoajTable.setDefaultRenderer(Object.class, new ColorRenderer()); // DEIXA A GRADE ZEBRADA

try {
            oUsuario.setCodigo_pessoa_usuario(recebe_codigo_pessoa);
            resultSet = oUsuario.getConsultar(conecta);
            if (resultSet.getRow() == 1){
             resultSet.first();
            }


        } catch (SQLException ex) {
            Logger.getLogger(Pessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            while (resultSet.next()) {

                modeloTabela.addRow(new String[]{
                    Funcoes.getCodigoFormat(resultSet.getInt("CODIGO_PESSOA_USUARIO")),
                    resultSet.getString("NOME_USUARIO"),
                    resultSet.getString("NIVEL_ACESSO")
                    
                });

            }

        } catch (SQLException ex) {
            Logger.getLogger(Pessoas.class.getName()).log(Level.SEVERE, null, ex);
        }

           }
    
    public void getFieldUsuarios(int codigo_click_usuario) throws ParseException{

        Usuarios oUsuario = new Usuarios();
        ResultSet rs;
        oUsuario.setCodigo_pessoa_usuario(codigo_click_usuario);

        try {
            rs = oUsuario.getConsultar(conecta);
            rs.next();

            //Pegar campos
            nomeUsuariojTextField.setText(rs.getString("NOME_USUARIO"));
//            senhajPasswordField.setText(rs.getString("SENHA"));
//            confirmarSenhajPasswordField.setText(rs.getString("SENHA"));
            nivelAcessojComboBox.setSelectedItem(rs.getString("NIVEL_ACESSO"));
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao preecher campos\n"+ex, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        buscarjButton.setVisible(true);
        novojButton.setVisible(true);
        editarjButton.setVisible(false);
        salvarjButton.setVisible(false);
        alterarjButton.setVisible(false);
        excluirjButton.setVisible(false);
        cancelarjButton.setVisible(false);
        nomeUsuariojTextField.grabFocus();
        try {
            ClassConecta.conecta();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir conexão com o banco de dados.\n"+e, 
                    "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
        
        nome_pessoajTextField.setText(recebe_nome_pessoa);
        
        buscarjButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowOpened

    private void novojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novojButtonActionPerformed
        // TODO add your handling code here:
        buscarjButton.setVisible(true);
        novojButton.setVisible(false);
        editarjButton.setVisible(false);
        salvarjButton.setVisible(true);
        alterarjButton.setVisible(false);
        excluirjButton.setVisible(false);
        cancelarjButton.setVisible(true);
        nomeUsuariojTextField.grabFocus();
        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(jFPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
        nomeUsuariojTextField.setText("");
        senhajPasswordField.setText("");
        repetirSenhajPasswordField.setText("");
        nivelAcessojComboBox.setSelectedItem("SELECIONE");
    }//GEN-LAST:event_novojButtonActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        if(nomeUsuariojTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Atenção!\n<html><body>O campo <b>\"Nome Usuário\" </b>é obrigatório</body></html>", 
            "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else if (senhajPasswordField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Atenção!\n<html><body>O campo <b>\"SENHA\" </b>é obrigatório</body></html>", 
            "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else if (repetirSenhajPasswordField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Atenção!\n<html><body>O campo <b>\"Repetir senha\" </b>é obrigatório</body></html>", 
            "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else if (senhajPasswordField.getText().length() != repetirSenhajPasswordField.getText().length()){
            JOptionPane.showMessageDialog(null, "Atenção!\nAs senhas não conferem", 
            "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else if(nivelAcessojComboBox.getSelectedItem().equals("SELECIONE")){
            JOptionPane.showMessageDialog(null, "Atenção!\n<html><body>O campo <b>\"Hierarquia\" </b>é obrigatório</body></html>", 
            "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else{  
            try {
                buscarjButton.setVisible(true);
                novojButton.setVisible(true);
                editarjButton.setVisible(false);
                salvarjButton.setVisible(false);
                alterarjButton.setVisible(false);
                excluirjButton.setVisible(false);
                cancelarjButton.setVisible(false);
                
                Usuarios oUsuarios = new Usuarios();             
                
                oUsuarios.setCodigo_pessoa_usuario(recebe_codigo_pessoa);
                oUsuarios.setNome_usuario(nomeUsuariojTextField.getText().trim().toUpperCase());
                oUsuarios.setNivel_acesso(nivelAcessojComboBox.getSelectedItem().toString());
                
                
                // CRIPTOGRAFA SENHA
                String senha = new String(senhajPasswordField.getPassword()); //CRIA UMA VARIAVEL TIPO STRING E PEGA A PASSWORD
                EncriptaSenha.encripta(senha);                           //ENVIA A SENHA DA VARIAVEL SENHA PARA A CLASSE ENCRIPTA SENHA E REALIZAA CRIPTOGRAFIA
                oUsuarios.setSenha(EncriptaSenha.encripta(senha));       //ENVIA A SENHA CRIPTOGRAFADA PARA A CLASSE
                oUsuarios.setCadastrar();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar o usuário\n"+e, "mensagem do sistema", JOptionPane.ERROR_MESSAGE);
            }
            buscarjButtonActionPerformed(evt);
        }
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void buscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarjButtonActionPerformed
        // TODO add your handling code here:
        try {
            getGradeusuarios();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar grade\n"+e, "mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
        int somaLinhas = gradeusuariosjTable.getModel().getRowCount();
        if(somaLinhas == 1){
            novojButton.setVisible(false);
        }
    }//GEN-LAST:event_buscarjButtonActionPerformed

    private void gradeusuariosjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeusuariosjTableMouseClicked
        // TODO add your handling code here:
        editarjButton.setVisible(true);
        codigo_click_usuario = Integer.parseInt(gradeusuariosjTable.getValueAt(gradeusuariosjTable.getSelectedRow(), 0).toString());  
        try {
            getFieldUsuarios(codigo_click_usuario);
        } catch (ParseException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao pegar dados da grade\n"+ex, "Mensagen do sistema", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_gradeusuariosjTableMouseClicked

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setVisible(false);
        editarjButton.setVisible(false);
        salvarjButton.setVisible(false);
        alterarjButton.setVisible(true);
        excluirjButton.setVisible(true);
        cancelarjButton.setVisible(true);
        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(jFPessoas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void alterarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarjButtonActionPerformed
        // TODO add your handling code here:
        if(nomeUsuariojTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Atenção!\n<html><body>O campo <b>\"Nome Usuário\" </b>é obrigatório</body></html>", 
            "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else if (senhajPasswordField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Atenção!\n<html><body>O campo <b>\"SENHA\" </b>é obrigatório</body></html>", 
            "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else if (repetirSenhajPasswordField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Atenção!\n<html><body>O campo <b>\"Repetir senha\" </b>é obrigatório</body></html>", 
            "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else if (senhajPasswordField.getText().length() != repetirSenhajPasswordField.getText().length()){
            JOptionPane.showMessageDialog(null, "Atenção!\nAs senhas não conferem", 
            "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else if(nivelAcessojComboBox.getSelectedItem().equals("SELECIONE")){
            JOptionPane.showMessageDialog(null, "Atenção!\n<html><body>O campo <b>\"Hierarquia\" </b>é obrigatório</body></html>", 
            "Mensagem do sistema", JOptionPane.WARNING_MESSAGE);
            
        }else{  
            try {
                buscarjButton.setVisible(true);
                novojButton.setVisible(true);
                editarjButton.setVisible(false);
                salvarjButton.setVisible(false);
                alterarjButton.setVisible(false);
                excluirjButton.setVisible(false);
                cancelarjButton.setVisible(false);
                
                Usuarios oUsuarios = new Usuarios();             
                
                oUsuarios.setCodigo_pessoa_usuario(recebe_codigo_pessoa);
                oUsuarios.setNome_usuario(nomeUsuariojTextField.getText().trim().toUpperCase());
                oUsuarios.setNivel_acesso(nivelAcessojComboBox.getSelectedItem().toString());
                
                
                // CRIPTOGRAFA SENHA
                String senha = new String(senhajPasswordField.getPassword()); //CRIA UMA VARIAVEL TIPO STRING E PEGA A PASSWORD
                EncriptaSenha.encripta(senha);                           //ENVIA A SENHA DA VARIAVEL SENHA PARA A CLASSE ENCRIPTA SENHA E REALIZAA CRIPTOGRAFIA
                System.out.println(EncriptaSenha.encripta(senha));
                oUsuarios.setSenha(EncriptaSenha.encripta(senha));       //ENVIA A SENHA CRIPTOGRAFADA PARA A CLASSE
                oUsuarios.setAlterar(conecta);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar o usuário\n"+e, "mensagem do sistema", JOptionPane.ERROR_MESSAGE);
            }
            buscarjButtonActionPerformed(evt);
        }
    }//GEN-LAST:event_alterarjButtonActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        // TODO add your handling code here:
        Object[] options = {"Sim", "Não"};
        int sd =
                JOptionPane.showOptionDialog(null, "Deseja realmente EXCLUIR esse registro?", "Confirmação!", JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        if (sd != 0) {
            return;
        }
        
        try {
            cancelarjButtonActionPerformed(evt);
        
            Usuarios oUsuario = new Usuarios();
        
            oUsuario.setCodigo_pessoa_usuario(codigo_click_usuario);
            oUsuario.setExcluir(conecta);
            
            nomeUsuariojTextField.setText("");
            senhajPasswordField.setText("");
            repetirSenhajPasswordField.setText("");
            nivelAcessojComboBox.setSelectedItem("SELECIONE");
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir registro\n"+e, "Mensagem do sistema", JOptionPane.ERROR_MESSAGE); 
        }
        buscarjButtonActionPerformed(evt);
    }//GEN-LAST:event_excluirjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
        buscarjButton.setVisible(true);
        novojButton.setVisible(true);
        editarjButton.setVisible(false);
        salvarjButton.setVisible(false);
        alterarjButton.setVisible(false);
        excluirjButton.setVisible(false);
        cancelarjButton.setVisible(false);
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jFUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarjButton;
    private javax.swing.JButton buscarjButton;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton editarjButton;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JTable gradeusuariosjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton limparjButton;
    private javax.swing.JComboBox nivelAcessojComboBox;
    private javax.swing.JTextField nomeUsuariojTextField;
    private javax.swing.JTextField nome_pessoajTextField;
    private javax.swing.JButton novojButton;
    private javax.swing.JPasswordField repetirSenhajPasswordField;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JPasswordField senhajPasswordField;
    // End of variables declaration//GEN-END:variables
}
